/*
 * Market Data API
 * The BraveNewCoin API is an HTTP API. The BraveNewCoin APIs provide market data information about crypto assets. 
 *
 * OpenAPI spec version: v3
 * Contact: support@bravenewcoin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.api.v3.client.autogen.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ErrorErrors
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-08-17T11:47:51.512+12:00[Pacific/Auckland]")
public class ErrorErrors {

  
  @JsonProperty("object")
  private String object = null;
  
  
  @JsonProperty("field")
  private String field = null;
  
  
  @JsonProperty("rejectedValue")
  private String rejectedValue = null;
  
  
  @JsonProperty("message")
  private String message = null;
  
  public ErrorErrors object(String object) {
    this.object = object;
    return this;
  }

  
  /**
  * The object that caused the error.
  * @return object
  **/
  
  
  @Schema(description = "The object that caused the error.")
  public String getObject() {
    return object;
  }
  public void setObject(String object) {
    this.object = object;
  }
  
  public ErrorErrors field(String field) {
    this.field = field;
    return this;
  }

  
  /**
  * The field that caused the error.
  * @return field
  **/
  
  
  @Schema(description = "The field that caused the error.")
  public String getField() {
    return field;
  }
  public void setField(String field) {
    this.field = field;
  }
  
  public ErrorErrors rejectedValue(String rejectedValue) {
    this.rejectedValue = rejectedValue;
    return this;
  }

  
  /**
  * The value which caused the error.
  * @return rejectedValue
  **/
  
  
  @Schema(description = "The value which caused the error.")
  public String getRejectedValue() {
    return rejectedValue;
  }
  public void setRejectedValue(String rejectedValue) {
    this.rejectedValue = rejectedValue;
  }
  
  public ErrorErrors message(String message) {
    this.message = message;
    return this;
  }

  
  /**
  * A message which usually provides a hint on how to resolve the error.
  * @return message
  **/
  
  
  @Schema(description = "A message which usually provides a hint on how to resolve the error.")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorErrors errorErrors = (ErrorErrors) o;
    return Objects.equals(this.object, errorErrors.object) &&
        Objects.equals(this.field, errorErrors.field) &&
        Objects.equals(this.rejectedValue, errorErrors.rejectedValue) &&
        Objects.equals(this.message, errorErrors.message);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(object, field, rejectedValue, message);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorErrors {\n");
    
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    rejectedValue: ").append(toIndentedString(rejectedValue)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



