/*
 * Market Data API
 * The BraveNewCoin API is an HTTP API. The BraveNewCoin APIs provide market data information about crypto assets. 
 *
 * OpenAPI spec version: v3
 * Contact: support@bravenewcoin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.api.v3.client.autogen.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Exchange
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-08-17T11:47:51.512+12:00[Pacific/Auckland]")
public class Exchange {

  
  @JsonProperty("id")
  private UUID id = null;
  
  
  @JsonProperty("name")
  private String name = null;
  
  
  @JsonProperty("url")
  private String url = null;
  
  /**
   * The status of the exchange
   */
  public enum StatusEnum {
    
    ACTIVE("ACTIVE"),
    INACTIVE("INACTIVE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    
    @JsonValue
    
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    
    @JsonCreator
    
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    
  }
  
  
  @JsonProperty("status")
  private StatusEnum status = null;
  
  
  @JsonProperty("markets")
  private List<ExchangeMarkets> markets = null;
  
  public Exchange id(UUID id) {
    this.id = id;
    return this;
  }

  
  /**
  * Unique identifier for the resource.
  * @return id
  **/
  
  
  @Schema(description = "Unique identifier for the resource.")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }
  
  public Exchange name(String name) {
    this.name = name;
    return this;
  }

  
  /**
  * The name of the exchange
  * @return name
  **/
  
  
  @Schema(description = "The name of the exchange")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  
  public Exchange url(String url) {
    this.url = url;
    return this;
  }

  
  /**
  * The URL of the exchange
  * @return url
  **/
  
  
  @Schema(description = "The URL of the exchange")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }
  
  public Exchange status(StatusEnum status) {
    this.status = status;
    return this;
  }

  
  /**
  * The status of the exchange
  * @return status
  **/
  
  
  @Schema(description = "The status of the exchange")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }
  
  public Exchange markets(List<ExchangeMarkets> markets) {
    this.markets = markets;
    return this;
  }

  public Exchange addMarketsItem(ExchangeMarkets marketsItem) {
    
    if (this.markets == null) {
      this.markets = new ArrayList<>();
    }
    
    this.markets.add(marketsItem);
    return this;
  }
  
  /**
  * The markets available on the exchange
  * @return markets
  **/
  
  
  @Schema(description = "The markets available on the exchange")
  public List<ExchangeMarkets> getMarkets() {
    return markets;
  }
  public void setMarkets(List<ExchangeMarkets> markets) {
    this.markets = markets;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Exchange exchange = (Exchange) o;
    return Objects.equals(this.id, exchange.id) &&
        Objects.equals(this.name, exchange.name) &&
        Objects.equals(this.url, exchange.url) &&
        Objects.equals(this.status, exchange.status) &&
        Objects.equals(this.markets, exchange.markets);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, name, url, status, markets);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Exchange {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    markets: ").append(toIndentedString(markets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



