/*
 * Market Data API
 * The BraveNewCoin API is an HTTP API. The BraveNewCoin APIs provide market data information about crypto assets. 
 *
 * OpenAPI spec version: v3
 * Contact: support@bravenewcoin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bnc.api.v3.client.autogen.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.UUID;

/**
 * Market
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-08-17T11:47:51.512+12:00[Pacific/Auckland]")
public class Market {

  
  @JsonProperty("id")
  private UUID id = null;
  
  
  @JsonProperty("baseAssetId")
  private UUID baseAssetId = null;
  
  
  @JsonProperty("quoteAssetId")
  private UUID quoteAssetId = null;
  
  public Market id(UUID id) {
    this.id = id;
    return this;
  }

  
  /**
  * Unique identifier for the resource.
  * @return id
  **/
  
  
  @Schema(description = "Unique identifier for the resource.")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }
  
  public Market baseAssetId(UUID baseAssetId) {
    this.baseAssetId = baseAssetId;
    return this;
  }

  
  /**
  * The base asset id which makes up the market
  * @return baseAssetId
  **/
  
  
  @Schema(description = "The base asset id which makes up the market")
  public UUID getBaseAssetId() {
    return baseAssetId;
  }
  public void setBaseAssetId(UUID baseAssetId) {
    this.baseAssetId = baseAssetId;
  }
  
  public Market quoteAssetId(UUID quoteAssetId) {
    this.quoteAssetId = quoteAssetId;
    return this;
  }

  
  /**
  * The quote asset id which makes up the market
  * @return quoteAssetId
  **/
  
  
  @Schema(description = "The quote asset id which makes up the market")
  public UUID getQuoteAssetId() {
    return quoteAssetId;
  }
  public void setQuoteAssetId(UUID quoteAssetId) {
    this.quoteAssetId = quoteAssetId;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Market market = (Market) o;
    return Objects.equals(this.id, market.id) &&
        Objects.equals(this.baseAssetId, market.baseAssetId) &&
        Objects.equals(this.quoteAssetId, market.quoteAssetId);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, baseAssetId, quoteAssetId);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Market {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    baseAssetId: ").append(toIndentedString(baseAssetId)).append("\n");
    sb.append("    quoteAssetId: ").append(toIndentedString(quoteAssetId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



